server:
  port: 8085
  error:
    whitelabel:
      enabled: false

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9093
      group-id: kafka-message-system
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "spring.json.trusted.packages": "com.examples.kafka.demo.models"

    producer:
      bootstrap-servers: localhost:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    mongodb:
      uri: mongodb://localhost:27017/db

logging:
  level:
    root: INFO